title: HeeDayDay
author: KOEUNHEE
email: heecode@naver.com
description: Github.io BLOG

github_username: heedayday
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: auto
# light-theme-accent-color: '#333'
# dark-theme-accent-color: '#eee'

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
